/**
 * Note entity interface representing a task/note in the system.
 */
export interface Note {
  _id: string;
  title: string;
  completed: boolean;
  dueDate: string | null;
  importance: number;
  createdAt?: number; // Auto-generated by NeDB
}

/**
 * DTO for creating a new note (without auto-generated fields).
 */
export type CreateNoteDto = Omit<Note, "_id" | "createdAt">;

/**
 * DTO for updating an existing note.
 */
export type UpdateNoteDto = Partial<Omit<Note, "_id" | "createdAt">>;
